set OS_PROJECT_DOMAIN_ID=default
set OS_USER_DOMAIN_ID=default
set OS_PROJECT_NAME=admin
set OS_TENANT_NAME=admin
set OS_USERNAME=admin
set OS_PASSWORD=Welcome123
set OS_AUTH_URL=http://172.16.69.140:35357/v3
set OS_VOLUME_API_VERSION=2
