heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: HaU14new
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: m1.small
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: my_key
  int_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
    default: int_net
  database_network:
    type: string
    label: Private network name or ID
    description: Public Network to attach instance to.
    default: priv_net    
  root_pass:
    type: string
    label: mysql root password
    description: mysql root password
    default: Welcome123
  db_name:
    type: string
    label: database name
    description: database name
    default: wordpress
  db_user:
    type: string
    label: database user
    description: database user
    default: wordpress
  db_pass:
    type: string
    label: database password
    description: database password
    default: Welcome123

resources:
  database:
    type: lib/mysql_instance.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      private_network: { get_param: database_network }
      root_pass: {get_param: root_pass}
      db_name: { get_param: db_name }
      db_user: { get_param: db_user }
      db_pass: { get_param: db_pass }
  wordpress:
    type: lib/wordpress_instance.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      int_network: { get_param: int_network }
      database_network: { get_param: database_network }
      mysql_server: { get_attr: [database, instance_ip] }
      db_name: { get_param: db_name }
      db_user: { get_param: db_user }
      db_pass: { get_param: db_pass }
    
      
outputs:
  web_name:
    description: Name of the webserver 
    value: { get_attr: [wordpress, name] }
  web_public_ip:
    description: Floating IP of Instance
    value: { get_attr: [wordpress, instance_public_ip ] }