heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: HaU14new
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: m1.small
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: my_key
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
    default: priv_net
  root_pass:
    type: string
    label: mysql root password
    description: mysql root password
    default: Welcome123
  db_name:
    type: string
    label: database name
    description: database name
    default: wordpress
  db_user:
    type: string
    label: database user
    description: database user
    default: wordpress
  db_pass:
    type: string
    label: database password
    description: database password
    default: Welcome123

resources:
  flask_secret_key:
    type: OS::Heat::RandomString
    properties:
      length: 32
      sequence: lettersdigits
  my_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - port: { get_resource: neutron_port }
      user_data: 
        str_replace:
          params:
            __ROOT_PASS__: { get_param: root_pass }
            __DB_NAME__: { get_param: db_name }
            __DB_USER__: { get_param: db_user }
            __DB_PASS__: { get_param: db_pass }
          template: |
            #!/bin/sh
            apt-get update -y
            echo mysql-server mysql-server/root_password password __ROOT_PASS__ | debconf-set-selections
            echo mysql-server mysql-server/root_password_again password __ROOT_PASS__ | debconf-set-selections
            apt-get -y install mariadb-server 
            sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/my.cnf
            #
            sed -i "/bind-address/a\default-storage-engine = innodb\n\
            innodb_file_per_table\n\
            collation-server = utf8_general_ci\n\
            init-connect = 'SET NAMES utf8'\n\
            character-set-server = utf8" /etc/mysql/my.cnf
            #
            service mysql restart
            #
            cat << EOF | mysql -uroot -p__ROOT_PASS__
            DROP DATABASE IF EXISTS __DB_NAME__;
            CREATE DATABASE __DB_NAME__;
            GRANT ALL PRIVILEGES ON __DB_NAME__.* TO '__DB_USER__'@'localhost' IDENTIFIED BY '__DB_PASS__';
            EOF
            #
            wget https://wordpress.org/wordpress-4.2.4.zip
            apt-get install -y unzip apache2 php5 php5-mysql
            unzip wordpress-4.2.4.zip
            mv wordpress /var/www/html/
            cd /var/www/html/
            chown -R root:www-data wordpress/
            cd wordpress
            mv wp-config-sample.php wp-config.php
            sed -i 's/database_name_here/__DB_NAME__/g' wp-config.php
            sed -i 's/username_here/__DB_USER__/g' wp-config.php
            sed -i 's/password_here/__DB_PASS__/g' wp-config.php
            #
            service apache2 restart
      user_data_format: RAW
  neutron_port:
    type: OS::Neutron::Port
    properties:
      admin_state_up: True
      network: int_net
      fixed_ips:
        - subnet: int_net
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 17a29699-5737-4645-85c6-a46460b4f136
      port_id: { get_resource: neutron_port }
      
outputs:
  instance_name:
    description: Name of the instance
    value: { get_attr: [my_instance, name] }
  instance_ip:
    description: IP address of the instance
    value: { get_attr: [my_instance, first_address] }
  instance_public_ip:
    description: Floating IP of Instance
    value: { get_attr: [ floating_ip, floating_ip_address ] }